### PR TITLE
Update plugin for Greebo

### PR DESCRIPTION
**Pull request by tqdv**
Changes:
* Update code for Greebo
* Add accesskey to the Changes button
* Add French translation

I tested the plugin for releases of Dokuwiki between Ponder Stibbons and Greebo. They work.

I also have another commit (not included in this pull request) that adds translation for other languages based on translatewiki.org, specifically, [this page](https://translatewiki.net/w/i.php?title=Special:Translations&message=MediaWiki%3AShowdiff), but I'm not sure it's a good idea.  
What do you think ?

### CODE REVIEW

**Comment by turnermm** [comment]
You say you tested this through Greebo,  but three of the functions that are called in your `_action_act_preprocess` have been removed from greebo.  If, for instance, you include this code at the top of that function:
```      
        if(function_exists('act_permcheck')) {
           msg('act_permcheck exists') ;
       }
       else  msg('act_permcheck does not exist') 
```
You should find that `act_permcheck` does not exist and, as far as I can see, the only reason that the wiki doesn't crash, is that the code which calls the missing functions is never reached.  At least that's been my experience.  You can verify that they are missing in the xref, that is they haven't been moved from action.php to another file.

**Comment by tqdv** [comment]
> the only reason that the wiki doesn't crash, is that the code which calls the missing functions is never reached.

That piece of code is a switch on the DokuWiki release.

`\dokuwiki\ActionRouter` only exists in release Greebo, so the `act_*` functions are only called in releases prior to it:
```php
if (class_exists('\\dokuwiki\\ActionRouter', false)) {
    /* ... */
} else
    if (/* Calls to act_* */) {
    /* Calls to act_* */
}
```

Since that wasn't clear, I clarified the version check and added a safeguard as you suggested:
```php
} elseif (function_exists('act_permcheck')) {
    /* Calls to act_* */
}
```
---
Also, does that mean that the differences view does not appear for you when testing ?

**Comment by turnermm** [comment]
On by-passing the missing functions, I get the diff header but no data.

**Comment by tqdv** [comment]
That's what happens when there are no differences between the latest revision and the current edit.  
Could you check if you did that ?

If you did add changes, then I don't know how that happened.

**Comment by turnermm** [comment]
Could you send me the link to your revised version?  I'm not sure I'm getting your revisions.

**Comment by tqdv** [comment]
My latest revision is here https://github.com/tqdv/dokuwiki-diffpreview/tree/greebo-fix. You can manually install it in DokuWiki with https://github.com/tqdv/dokuwiki-diffpreview/zipball/greebo-fix.

Or maybe are you referring to this:
> That's what happens when there are no differences between the latest revision and the current edit.

I was saying that if there are no differences between the latest revision of the page and the current edit text, then only the header of the diff is shown.

---

I retested with a brand new Greebo install, and it works as expected.

**Comment by turnermm** [comment]
Solved.  Sorry @tqdv. I didn't realize that a third developer had entered the upgrade.  It now works as it is supposed to.  If you don't hear back from the original plugin author or current maintainer, maybe you can update the plugin page and substitute your download link for his, until you hear from him.  That way we'll have a working updated plugin.

**Comment by issmirnov** [comment]
Hi gents, apologies for the radio silence. My email filters were too aggressive. Looks good to me, merging.

**Comment by issmirnov** [comment]
Would you two be interested in being added as collaborators on this project? I originally forked it due to upstream repo getting really out of date.

Edit: Ah, I see the download link at https://www.dokuwiki.org/plugin:diffpreview already points to https://github.com/tqdv/dokuwiki-diffpreview. Perfect - carry the baton well, friend! :)

**Pull request merged**
